export const formatCurrency = (amount, currencySymbol = '₹') => {
  const value = parseFloat(amount) || 0;
  return `${currencySymbol} ${value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

export const getInvoiceStatus = (invoice) => {
  if (parseFloat(invoice.paid) >= parseFloat(invoice.total)) return 'paid';
  if (parseFloat(invoice.paid) > 0) return 'partial';
  if (invoice.due_date && new Date(invoice.due_date) < new Date()) return 'overdue';
  return invoice.status || 'unpaid';
};

export const generateInvoiceNumber = (prefix, lastNumber) => {
  const num = parseInt(String(lastNumber).replace(/\D/g, ''), 10) + 1;
  return `${prefix}${String(num).padStart(4, '0')}`;
};

export const calculateItemAmount = (quantity, unitPrice, gstRate) => {
  const baseAmount = quantity * unitPrice;
  const gstAmount = baseAmount * (gstRate / 100);
  return baseAmount + gstAmount;
};

export function calcInvoiceTotals(items, discount = 0, roundOff = 0, shippingCharges = 0) {
  let subtotal = 0;
  let gstAmount = 0;
  for (const item of items) {
    const qty = parseFloat(item.qty) || 0;
    const price = parseFloat(item.price) || 0;
    const gst = parseFloat(item.gst) || 0;
    const itemDiscountPercent = parseFloat(item.discount) || 0;
    const base = qty * price;
    const itemDiscountAmount = base * (itemDiscountPercent / 100);
    const taxable = base - itemDiscountAmount;
    subtotal += taxable;
    gstAmount += taxable * (gst / 100);
  }
  const disc = parseFloat(discount) || 0;
  const shipping = parseFloat(shippingCharges) || 0;
  const round = parseFloat(roundOff) || 0;
  const total = subtotal + gstAmount - disc + shipping + round;
  return { subtotal, gstAmount, discount: disc, shippingCharges: shipping, roundOff: round, total: Math.max(0, total) };
}

export function splitGst(gstAmount, isInterState = false) {
  const gst = parseFloat(gstAmount) || 0;
  if (isInterState) return { igst: gst, cgst: 0, sgst: 0 };
  return { cgst: gst / 2, sgst: gst / 2, igst: 0 };
}

export function buildWhatsAppUrl(phone, message) {
  const digits = (phone || '').replace(/\D/g, '');
  const num = digits.length === 10 ? `91${digits}` : digits;
  return `https://wa.me/${num}?text=${encodeURIComponent(message)}`;
}

export function buildInvoiceWhatsAppMessage(invoice, customer, businessName, currencySymbol = '₹') {
  const status = getInvoiceStatus(invoice);
  const statusEmoji = status === 'paid' ? '✅' : status === 'partial' ? '⏳' : status === 'overdue' ? '⚠️' : '📄';
  
  let message = `*${businessName}*\n\n`;
  message += `${statusEmoji} *Invoice ${invoice.invoice_no}*\n`;
  message += `👤 Customer: ${customer?.name || 'N/A'}\n`;
  message += `📅 Date: ${formatDate(invoice.date)}\n`;
  message += `💰 Total: ${formatCurrency(invoice.total, currencySymbol)}\n`;
  message += `💳 Paid: ${formatCurrency(invoice.paid, currencySymbol)}\n`;
  message += `⏳ Balance: ${formatCurrency(invoice.balance, currencySymbol)}\n`;
  
  if (invoice.due_date) {
    const dueStatus = new Date(invoice.due_date) < new Date() ? 'OVERDUE' : 'Due';
    message += `📆 ${dueStatus}: ${formatDate(invoice.due_date)}\n`;
  }
  
  if (status !== 'paid') {
    message += `\n🙏 Please clear the balance at your earliest convenience.\n`;
  } else {
    message += `\n✅ Payment received. Thank you for your business!\n`;
  }
  
  message += `\nFor details, contact us.\n`;
  message += `Generated by BillBook App`;
  
  return message;
}

export function buildPaymentReminderMessage(invoice, customer, businessName, currencySymbol = '₹') {
  let message = `*${businessName} - Payment Reminder*\n\n`;
  message += `Dear ${customer?.name || 'Customer'},\n\n`;
  message += `This is a friendly reminder that your invoice ${invoice.invoice_no} `;
  message += `is due on ${formatDate(invoice.due_date)}.\n\n`;
  message += `📋 Invoice Details:\n`;
  message += `• Invoice No: ${invoice.invoice_no}\n`;
  message += `• Total Amount: ${formatCurrency(invoice.total, currencySymbol)}\n`;
  message += `• Outstanding Balance: ${formatCurrency(invoice.balance, currencySymbol)}\n`;
  message += `• Due Date: ${formatDate(invoice.due_date)}\n\n`;
  message += `Please arrange for payment at your earliest convenience.\n\n`;
  message += `If you have already paid, please ignore this message.\n\n`;
  message += `Thank you for your business!\n`;
  message += `${businessName}`;
  
  return message;
}

export function buildThankYouMessage(invoice, customer, businessName, currencySymbol = '₹') {
  let message = `*${businessName} - Payment Received*\n\n`;
  message += `Dear ${customer?.name || 'Customer'},\n\n`;
  message += `Thank you for your payment of ${formatCurrency(invoice.paid, currencySymbol)} `;
  message += `for invoice ${invoice.invoice_no}.\n\n`;
  message += `📋 Payment Details:\n`;
  message += `• Invoice No: ${invoice.invoice_no}\n`;
  message += `• Amount Received: ${formatCurrency(invoice.paid, currencySymbol)}\n`;
  message += `• Remaining Balance: ${formatCurrency(invoice.balance, currencySymbol)}\n\n`;
  message += `We appreciate your prompt payment.\n\n`;
  message += `Looking forward to serving you again!\n\n`;
  message += `${businessName}`;
  
  return message;
}

export function getDocumentDetailRoute(documentKind) {
  const routes = {
    sale_invoice: '/invoices', quotation: '/quotations', estimate: '/estimates',
    proforma_invoice: '/proforma', delivery_challan: '/delivery-challans',
    credit_note: '/credit-notes', purchase_order: '/purchases', debit_note: '/debit-notes',
  };
  return routes[documentKind] || '/invoices';
}

export function addDays(dateStr, days) {
  const d = dateStr ? new Date(dateStr) : new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export function exportToCSV(filename, headers, rows) {
  const escape = (val) => {
    const str = String(val ?? '');
    return str.includes(',') || str.includes('"') || str.includes('\n')
      ? `"${str.replace(/"/g, '""')}"`
      : str;
  };
  const csv = [headers.map(escape).join(','), ...rows.map((row) => row.map(escape).join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}

export function importFromCSV() {
  return new Promise((resolve, reject) => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.csv';
    input.onchange = (e) => {
      const file = e.target.files[0];
      if (!file) {
        resolve(null);
        return;
      }
      const reader = new FileReader();
      reader.onload = (event) => {
        const text = event.target.result;
        const lines = text.split('\n').filter(line => line.trim());
        if (lines.length < 2) {
          resolve([]);
          return;
        }
        const headers = parseCSVLine(lines[0]);
        const data = lines.slice(1).map(line => {
          const values = parseCSVLine(line);
          const obj = {};
          headers.forEach((header, index) => {
            obj[header.trim()] = values[index] || '';
          });
          return obj;
        });
        resolve(data);
      };
      reader.onerror = reject;
      reader.readAsText(file);
    };
    input.click();
  });
}

function parseCSVLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

export function formatDate(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-IN');
}

export const PAYMENT_MODES = ['Cash', 'Bank Transfer', 'UPI', 'Cheque', 'Credit Card'];

export const EXPENSE_CATEGORIES = [
  'Rent', 'Utilities', 'Transportation', 'Office Supplies',
  'Maintenance', 'Salaries', 'Marketing', 'Other',
];
